
SELECT T.ID
FROM ECOLI_DATA F
JOIN ECOLI_DATA S ON F.ID = S.PARENT_ID
JOIN ECOLI_DATA T ON S.ID=T.PARENT_ID
WHERE F.PARENT_ID IS NULL
ORDER BY T.ID ASC;

# SELECT T.ID
# FROM ECOLI_DATA F  -- 1세대 (First)
# JOIN ECOLI_DATA S ON F.ID = S.PARENT_ID -- 2세대 (Second)
# JOIN ECOLI_DATA T ON S.ID = T.PARENT_ID -- 3세대 (Third)
# WHERE F.PARENT_ID IS NULL -- 1세대는 부모가 없어야 함
# ORDER BY T.ID ASC;